/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

interface DeployedContracts {
  [networkId: number]: { [contractName: string]: ContractInfo };
}

interface ContractInfo {
  address: string;
  abi: any[]; // Consider using a more specific type for ABI if possible
  inheritedFunctions?: Record<string, unknown>;
}

let deployedContracts: DeployedContracts = {
  1: {
    YourContract: {
      address: "0x0000000000000000000000000000000000000000",
      abi: [
        // ABI details omitted for brevity
      ],
      inheritedFunctions: {},
    },
  },
};

// Function to update deployedContracts with new data from updateDeployedContract
function updateContracts(updateDeployedContract: { networkId: number; contractName: string; address: string; abi: any[] }) {
  if (updateDeployedContract) {
    const { networkId, contractName, address, abi } = updateDeployedContract;

    if (!deployedContracts[networkId]) {
      deployedContracts[networkId] = {};
    }

    deployedContracts[networkId][contractName] = {
      address,
      abi,
      inheritedFunctions: {}, // Reset or keep empty as per requirement
    };
    console.log('deployedContracts:', deployedContracts);
  }
}

// // Call the function to perform the update if updateDeployedContract is available
export { updateContracts };

export default deployedContracts satisfies GenericContractsDeclaration;